### ISSUE TITLE
Duplicated texts using cytoscape.js-edgehandles

### ISSUE THREAD

**Issue by darkoromanov** [kaluginserg/cytoscape-node-html-label#11]
I'm using the extension cytoscape.js-edgehandles and there's a weird issue when hovering handles: it duplicates the HTML with "undefined" as texts.

![bug](https://user-images.githubusercontent.com/711784/42624244-3699b0cc-85c5-11e8-969a-fbc8eaba66e1.PNG)

When the node lost its focus then the duplicated text is removed.

**Comment by kaluginserg** [comment]
Hm, I did not test the extension for compatibility with other extensions. May be, the behavior is dependency on internal logic cytoscape.js-edgehandles. May be the cytoscape.js-edgehandles create new "fake cytoscape node" for red circle, and may be so the html-label detect it...

Do you have any further details?

**Comment by darkoromanov** [comment]
Sorry for the late response but I followed the suggestion of @maxkfranz The issue appeared when I was using the query "node" (so all kind of nodes) now I'm using a specific selector (node[type = "milestone"]) and I don't have the issue anymore.
