### ISSUE TITLE
HTML label not moved when node position changes

### ISSUE THREAD

**Issue by cversari** [kaluginserg/cytoscape-node-html-label#15]
Hello,
  I have noticed that the HTML label follows the node when the node is dragged, but it stays in place if the node's position() is changed directly via javascript. This happens because in the function cyNodeHtmlLabel() the handler is bound to the "drag" event instead of the "position" event (that apparently includes the "drag" event too). This [change](https://github.com/kaluginserg/cytoscape-node-html-label/files/2312383/patch.txt) fixes the issue for me.

Cristian

**Comment by morficus** [comment]
@cversari you should open a PR for this. Hopefully that way this issue can get fixed in the next release :-)
