### ISSUE TITLE
Allow React nodes as labels

### ISSUE THREAD

**Issue by smith** [kaluginserg/cytoscape-node-html-label#19]
This is 1/2 feature request and 1/2 curiosity as to how it would be done. Instead of a template, I'd like to pass in a react component, which essentially has the same `(data) => DOM` API as the template, but renders a node instead of a string.

I'm going to play with using React's render to string method, but I don't think that will work with event handlers.

I think it would be possible, but will have to dig into the code to figure it out. Any guidance or opinions would be helpful.

**Comment by nickyromeijn** [comment]
This would be awesome, I'm really interested if there's been any progress on this issue

**Comment by smith** [comment]
We're using another component that tracks the node positions and renders a layer of react elements "on top of" the graph. It seems to work well and I probably won't go about implementing this.

I'm going to close the ticket, but if somebody were to implement it I would definitely be interested.

**Comment by nickyromeijn** [comment]
@smith Would you mind sharing what component that is?

**Comment by smith** [comment]
It's not open source, unfortunately. There's a cytoscape components that forceUpdates every time certain events happen (mostly viewport) and then a child-as-function component that takes the cytoscape object and creates react elements from at the node positions, so something like:

```javascript
<Cytoscape options={...}>{cytoscape => { 
   // something with cytoscape.pan(), .zoom(), .height()
   const transformedStyle = { position: 'absolute', transform: `translate(${x}px,${y - height}px) scale(${zoom})` }
   return <div style={transformedStyle}>{cy.nodes().map(node =>
	  <Node {... style props from the node object to position the node} />
   )}</div>
}}</Cytoscape>
```

hope that makes sense.

**Comment by nickyromeijn** [comment]
@smith Yeah, figured it would be something like that. Thanks 👍

**Comment by tsi** [comment]
This works for me:
```
import { renderToString } from 'react-dom/server';
...
cy.nodeHtmlLabel([
  {
    query: 'node[label]', // cytoscape query selector
    tpl(data) {
      return renderToString(<ItemLabel data={data} />);
    }
  }
]);
```

**Comment by alexrigby** [comment]
@tsi Could you let me know how you sucessfully registered the nodeHtmlLable function to your instance of cytoscape in React? 

I am having trouble importing the library and then using the library with my cy instance. 

I am converting my plain js project to React but my program errors when I try to register my cy Instace (created with cytoscape-react).  The messages complains that 'cy is not a function'. 

Any further details of how you got the library working with react would be really helpfull!!
