### ISSUE TITLE
Performance when moving the/zooming the graph

### ISSUE THREAD

**Issue by karlitos** [kaluginserg/cytoscape-node-html-label#2]
The [example you provide in the Readme](https://kaluginserg.github.io/cytoscape-node-html-label/) shows serious performance issues (tested on Chrome 60 and Firefox 46).

The position/size of the labels changes with noticeable delay when moving/zooming the graph. The overall performance does not feel very smooth.

![cytoscape-node-html-label](https://user-images.githubusercontent.com/3693437/29029835-452b7220-7b89-11e7-92fe-91db33fa2ace.gif)

**Comment by kaluginserg** [comment]
Thank you. Soon, the rendering procedure will be rewriting.

**Comment by kaluginserg** [comment]
#3 Performance was improved in new extension version.
