### ISSUE TITLE
NPM published version of package not available on GitHub

### ISSUE THREAD

**Issue by smith** [kaluginserg/cytoscape-node-html-label#38]
The [published NPM package](https://www.npmjs.com/package/cytoscape-node-html-label) is version 1.2.0, but as of 070da3a the latest tag is 1.1.5 and the package.json shows 1.1.5.

Was a newer version published as 1.2.0 but not here?

**Comment by josejulio** [comment]
Sorry for the confusion, i forgot to push the commits of the version bump when doing the last release.
